apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
  name: openldap
  namespace: openldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: openldap
    spec:
      containers:
      - env:
        - name: LDAP_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: LDAP_BASE_DN
              name: ldap-conf
        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_DOMAIN
              name: ldap-conf
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: ldap-admin-pwd
        - name: LDAP_READONLY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_READONLY_USER_PASSWORD
              name: ldap-readonly-pwd
        - name: LDAP_READONLY_USER
          valueFrom:
            configMapKeyRef:
              key: LDAP_READONLY_USER
              name: ldap-conf
        image: docker.io/osixia/openldap@sha256:11a30708d9224291c39b2eed1d2620eb9687f4b8411e3b9dac6362ff634794c2
        imagePullPolicy: IfNotPresent
        name: openldap
        ports:
        - containerPort: 389
          protocol: TCP
        - containerPort: 636
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: openldap
      serviceAccountName: openldap
      terminationGracePeriodSeconds: 30