[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
  '''deployments\/openldap\/openldap-template.yaml''',
  '''deployments\/openldap\/phpldapadmin-template.yaml''',
  '''deployments\/openldap\/ansible-automation-env-template.yaml''',
  '''certificates\/''',
  '''deployments\/sealed-secrets\/secret.yaml''',
  '''deployments\/auth-server\/ldap-secret.yaml''',
  '''setup.py'''
]