[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''\/manifests\/openldap\/adminsecret.yaml''',
    '''\/manifests\/openldap\/readonlysecret.yaml''',
  ]