[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
  '''\/deployments\/openldap\/adminsecret.yaml''',
  '''\/deployments\/openldap\/readonlysecret.yaml'''
]