apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: openldap-template
  annotations:
    description: "Template to deploy OpenLDAP with required resources"
parameters:
  - name: OPENLDAP_NAMESPACE
    displayName: "OpenLDAP Namespace"
    required: true
objects:
  # Namespace
  - kind: Project
    apiVersion: v1
    metadata:
      name: ${OPENLDAP_NAMESPACE}

  # Secrets
  - kind: SealedSecret
    apiVersion: bitnami.com/v1alpha1
    metadata:
      name: ldap-readonly-pwd
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      encryptedData:
        LDAP_READONLY_USER_PASSWORD: AgBAVxd3ZijBax18XNZNgRAWihqVhmxtQl7EmPTSYgqIF3+kIpwNFW4B8DtyXCaVX7Xl+Pj/g6YZxf6TYtk9pVlyQ92brD3xxmR16Cd3HFWDTbvrRhyAvVrWGHfB5wAxLbWIs7gS/3vp0Fp9z0TF18OvZutom0wyuBNJB5olAdzDQalhtLQKfmyfAfIKI+FFDBECsjYzWJfxSXuAK3EABvUMJDvS7vArNPYj+VLdvR0LfjO02crD1dy37Co3nGaK+Pt6A11RY/h+GJIaqq+2E8vHXX7S6YQo/mLh0TRyw2vWSF/oF+ehkp/Zx9t9/vABp2SqcaXKPJ9SLVmjwzNYu/Vg5LsCSVTypnFB4ub73qDzJsm1Pns3y0U+g38bXXHTatDJlGtUtpPDvChJ08LW/YnXvIzO6cZnlH3odD5/1mt8Pb10qlhDmAZv9boTQiiKpCNVga33mDrRNcZmOJNBf2KUzZkeqyOzcblDVPZ8I0U5LlPi5RHf2hVbRsHSxg9JxMSR++ywuI9LGpRpdjhsjtq00zx99HzLSdr80ViAcdqWdWR1yjJEj1jkZ+/kRgbJxXnHnM7oBCsI4mO/xZa1tjppIL2bu5AKEIE88pD0o74/OSt3opnWdNVOfLqg8By0pPx6NXdSoBcPgbOH/g3ID2lhcqe2eZadmaJ+RQ0qbSz1RxsHTrLMTj7Rw4mn2/O2tJ2kT3GEhgIIJNqfFQ==
      template:
        metadata:
          name: ldap-readonly-pwd
          namespace: ${OPENLDAP_NAMESPACE}
    
  - kind: SealedSecret
    apiVersion: bitnami.com/v1alpha1
    metadata:
      name: ldap-admin-pwd
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      encryptedData:
        LDAP_ADMIN_PASSWORD: AgBvg77CQmNqhEV/S/PCuWW120rVS77svet+3NxuUiPOb3dzEIaxx7KSy4SIBFKbXBCLiiL2SPF+ciYh8w+ltCyu8UlU3P69ye8B76icNNCJxLR0ygygkFkLc0x4xBoD5QN+46c+aSSVMQgA5Eqbey6L/vGndbAi2pbNxjinwiqPFkW1hMDiNFxyicLROXrBBzaxjIWYRVWjbojTmgMF0zqhsMIn3wqh8vYujeDNFvIwwcjTt/ufpLAxILaJXDNNZi/AfoC1MVGIxaJo0YitQFlyIrfTl7G6oLYlknO0QaMhTo+J/9hU9EwltHvTqnNBgynP8bD0HmJHb2zVkdbAxk2k6Doc9gZWplnDhQOEHr3rPzqIvhWBKpOxLB+1Bd2uC30sC0Ym6W3iK/bNI7QvOz2cGQc3Vvu4bxmNCZe70MlBY8DqyYyrAElsS+i6gE2r6cjnV0GPu6XSrN8Oycy7uokMZW4njRriGW0FNDq8QmzlnngNrtOdyL0DNiMQc7TydDAVEi8HV2IWHxUPdWEtxE+2kRCL4shCQmS+3ubUUsoXsAyzJKTB58nbl6l8hC/vwZkEKl4n5LJ5oTrOeuIg/rIgY4q6GFaH5mqOe8Q4dItj6cUaBlbWGymFIMXV5a05hwrlcyWjamsHSoq3E2bFe8JzJP+hVdxTUjvLi3xb060EdnnSAWcWkpsGZfrJXpLhlPDWwthzuowong==
      template:
        metadata:
          name: ldap-admin-pwd
          namespace: ${OPENLDAP_NAMESPACE}



  # ConfigMap
  - kind: ConfigMap
    apiVersion: v1
    data:
      LDAP_BASE_DN: dc=wayneenterprises,dc=org
      LDAP_DOMAIN: wayneenterprises.org
      LDAP_READONLY_USER: "true"
    metadata:
      name: ldap-conf
      namespace: ${OPENLDAP_NAMESPACE}

  # ServiceAccount
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: openldap
      namespace: ${OPENLDAP_NAMESPACE}

  # RoleBinding
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: openldap
      namespace: ${OPENLDAP_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:anyuid
    subjects:
    - kind: ServiceAccount
      name: openldap
      namespace: ${OPENLDAP_NAMESPACE}
  
  # Database and config PVC
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: database-pv-claim
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "3Gi"

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: configuration-pv-claim
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: "1Gi"

  # Deployment
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: openldap
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          deployment: openldap
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            deployment: openldap
        spec:
          volumes:
            - name: database-storage
              persistentVolumeClaim:
                claimName: database-pv-claim
            - name: configuration-storage
              persistentVolumeClaim:
                claimName: configuration-pv-claim
          containers:
          - name: openldap
            image: docker.io/osixia/openldap@sha256:11a30708d9224291c39b2eed1d2620eb9687f4b8411e3b9dac6362ff634794c2
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: database-storage
                mountPath: /var/lib/ldap
              - name: configuration-storage
                mountPath: /etc/ldap/slapd.d
            ports:
            - containerPort: 389
              protocol: TCP
            - containerPort: 636
              protocol: TCP
            env:
            - name: LDAP_BASE_DN
              valueFrom:
                configMapKeyRef:
                  name: ldap-conf
                  key: LDAP_BASE_DN
            - name: LDAP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ldap-conf
                  key: LDAP_DOMAIN
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-admin-pwd
                  key: LDAP_ADMIN_PASSWORD
            - name: LDAP_READONLY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-readonly-pwd
                  key: LDAP_READONLY_USER_PASSWORD
            - name: LDAP_READONLY_USER
              valueFrom:
                configMapKeyRef:
                  name: ldap-conf
                  key: LDAP_READONLY_USER
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: Always
          serviceAccountName: openldap
          terminationGracePeriodSeconds: 30

  # Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: openldap
      namespace: ${OPENLDAP_NAMESPACE}
    spec:
      ports:
      - name: 389-tcp
        port: 389
        protocol: TCP
        targetPort: 389
      - name: 636-tcp
        port: 636
        protocol: TCP
        targetPort: 636
      selector:
        deployment: openldap
      type: ClusterIP
