apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sealed-secrets
namespace: sealed-secrets
resources:
- secret.yaml
- controller.yaml

patches:
- target:
    kind: Deployment
    name: sealed-secrets-controller
    group: apps
    version: v1
  path: sc-patch.yaml