apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: group-syncer-template
  annotations:
    description: "Template to deploy the LDAP group syncer cronjob"
parameters:
  - name: GROUP_SYNCER_NAMESPACE
    displayName: "Group syncer cronjob Namespace"
    required: true
objects:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: ${GROUP_SYNCER_NAMESPACE}
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: ldap-group-syncer
      namespace: ${GROUP_SYNCER_NAMESPACE}
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ldap-group-syncer
    rules:
    - apiGroups:
      - user.openshift.io
      resources:
      - groups
      verbs:
      - get
      - list
      - create
      - update
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ldap-group-syncer
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ldap-group-syncer
    subjects:
    - kind: ServiceAccount
      name: ldap-group-syncer
      namespace: ${GROUP_SYNCER_NAMESPACE}
  - kind: SealedSecret
    apiVersion: bitnami.com/v1alpha1
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ldap-secret
      namespace: ${GROUP_SYNCER_NAMESPACE}
    spec:
      encryptedData:
        bindPassword: AgCkt+KQQEzBUQ3Ioik/GZ2lKht1iC5RTZ0TLBJLuReLWL/ni0CncYe1eTPrqTRLp4X9NGvFzcT5wcH1IqwQUnhG+d8Klv/ev+rkkdveqK7DM+HifWZCLvOLn/IMs6e0OGd1ad0noL3zqf41PWasveEbjxp/AgOjny11YJztaUUam/B/4KyQNFG5hcgQLtauGH/eDaPojnhJuaCdPYgkaoBnby96Y7nqnipFvj6iYXsQ3wspOpgdYY4OicKrO8agrnXWhMR4yiCoHFfo2I2iDw70zWfOxGNc1GBnzqzAWv3bUaAhmUs02eSOYsUzMx5iXSToPiBcIAylg6dPdBELLlf+mbzlYvzlMeZw+e/iVwGOLv+a1DCJi1OdiD9vcfMM6cWdWwaWqgcxjmvWo+RpMBXMPWoL7lAp4lG3SngFKLHidiiYZ5kIR74zoLszMEhccTPsXSW7l4I9pxyDznsR08FLiozjlbCkWiE57TZFDlAT7mGCmyPvgMejYLQkCKAE41UQrD/KJQfO6Qm5bMy+rB+3riIgR4tEp8+Ynq0jeKcIxpmbuawK27SGuq4ZFE1xz/mttm5rQR/Rqt5MYi+2J82ioCj0M9U1xVhpQyTg3tbbzChuF6an2zsAsrpXjUbs+jQv92N1TOsNNSKohqpPp2cYj6ZqpT3g0w2LKImiYQc/iLabgn3xejEQzz+IZEcAQNefw9YhWqunN+vGxA==
      template:
        metadata:
          annotations:
            sealedsecrets.bitnami.com/cluster-wide: "true"
          creationTimestamp: null
          name: ldap-secret
          namespace: ${GROUP_SYNCER_NAMESPACE}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ldap-group-sync
      namespace: ${GROUP_SYNCER_NAMESPACE}
    data:
      ldap-sync.yaml: |                                 
        kind: LDAPSyncConfig
        apiVersion: v1
        url: ldap://openldap.openldap.svc.cluster.local:389                  
        bindDN: cn=readonly,dc=wayneenterprises,dc=org
        bindPassword:
          file: /etc/secrets/bindPassword
        insecure: true   
        augmentedActiveDirectory:
            groupsQuery:
                baseDN: "ou=groups,dc=wayneenterprises,dc=org"
                scope: sub
                derefAliases: never
                pageSize: 0
            groupUIDAttribute: dn 
            groupNameAttributes: [ cn ] 
            usersQuery:
                baseDN: "ou=people,dc=wayneenterprises,dc=org"
                scope: sub
                derefAliases: never
                filter: (objectclass=inetOrgPerson)
                pageSize: 0
            userNameAttributes: [ uid ] 
            groupMembershipAttributes: [ memberOf ] 
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ldap-group-sync
      namespace: ${GROUP_SYNCER_NAMESPACE}
    spec:
      schedule: "*/1 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              restartPolicy: Never
              containers:
                - name: ldap-group-sync
                  image: "docker.io/appuio/oc:v4.15"
                  command:
                    - "/bin/sh"
                    - "-c"
                    - "oc adm groups sync --sync-config=/etc/config/ldap-sync.yaml --confirm"
                  volumeMounts:
                    - mountPath: "/etc/config"
                      name: "ldap-sync-volume"
                    - mountPath: "/etc/secrets"
                      name: "ldap-bind-password"
              volumes:
                - name: "ldap-sync-volume"
                  configMap:
                    name: "ldap-group-sync"
                - name: "ldap-bind-password"
                  secret:
                    secretName: "ldap-secret"
              serviceAccountName: ldap-group-syncer
              serviceAccount: ldap-group-syncer