apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ansible-automation-env-template
  annotations:
    description: "Template to deploy Ansible automation job with required resources"
parameters:
  - name: ANSIBLE_NAMESPACE
    displayName: "Ansible Namespace"
    required: true
  - name: ANSIBLE_REPOSITORY
    displayName: "Repository with the Ansible playbook to execute"
    required: true
objects:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: ${ANSIBLE_NAMESPACE}
  
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
  
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:anyuid
    subjects:
    - kind: ServiceAccount
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}

  - kind: SealedSecret
    apiVersion: bitnami.com/v1alpha1
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vault-password
      namespace: ${ANSIBLE_NAMESPACE}
    spec:
      encryptedData:
        vault-password.txt: AgAZfzZtkR/ws4y/DLqylA5evTWTypIkUd5y5IX4JKUEBzxx1sI15v90vTpus2n6DlpFBt7hZDmTnjZj15x5oXUiVQeYJ8hyItDnRKlB+D57dRVO8m3vWWTofXxNNhe6J9fwrXLmQM11aZ9016T44WWLTdxj+HTdSJJmOUmUEk0r0n39kbzKL5L81fYwisEZhUHeubrIMJLrHbJmoPVDSZke05qK6RcYG4CAtWifA4bnIBn0KowSdnph9pG3UAYKmG8qG2hAh1YlbjSiBO7Jj0lIzbKGs6Wivtofb4Z2gWxNGvjf4yeWFT2lC74vdIknl7QDf735savJGXDgChcNKI2eTTjqcFXJ5lXdmPxnPGwZhgmpr3AZTiJyy0JPnJVYWZIPvQiQfO1hKZlQmkCrTQXJvO94um+7uL1ycEU8v+++NrIKMXMduA0oJsT4cGiq+AJ7z/VxPLvEQAGXZom7T0ihP/Rlxz17cwjiLqey2EvNYHurv/M12jMH+Ne2oDvA9zbsGwB4lfJ8JW2SWXZ/fLtrg1QlDbBvMJjXdSZe9VtxlTINyQVjCy0CwhVSebw5Q98NI4OZb2cr+mkeT4G6qzsc0sMSbovGozspW/fltzvDxqg7X1sGbdRw/nzzEUCK5b9P0uG7IQ8JGfNfQNholRE7+VNszfaJzzxd0UGzj7fWpHHvvTjeJW6MYGX6tTzbKK8zBcuMIhRFYbu6Og==
      template:
        metadata:
          annotations:
            sealedsecrets.bitnami.com/cluster-wide: "true"
          creationTimestamp: null
          name: vault-password
          namespace: ${ANSIBLE_NAMESPACE}
    
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
            - name: git-clone
              image: "docker.io/alpine/git:v2.47.1"
              args:
              - clone
              - ${ANSIBLE_REPOSITORY}
              - /repo
              volumeMounts:
                - name: git-repo-volume
                  mountPath: /repo   
          containers:
            - name: ansible
              image: "docker.io/alpine/ansible:2.16.1"
              args:
              - "ansible-playbook"
              - "/repo/ansible/populateldap.yaml"
              - "--vault-password-file"
              - "/vault/vault-password.txt"
              volumeMounts:
                - name: git-repo-volume
                  mountPath: /repo 
                - name: vault-password
                  mountPath: /vault  
          serviceAccountName: ansible
          volumes:
            - name: git-repo-volume
              emptyDir: {}  
            - name: vault-password
              secret:
                secretName: vault-password
