apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ansible-automation-env-template
  annotations:
    description: "Template to deploy Ansible automation job with required resources"
parameters:
  - name: ANSIBLE_NAMESPACE
    displayName: "Ansible Namespace"
    required: true
objects:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: ${ANSIBLE_NAMESPACE}
  
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
  
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:anyuid
    subjects:
    - kind: ServiceAccount
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}

  - kind: SealedSecret
    apiVersion: bitnami.com/v1alpha1
    metadata:
      name: vault-password
      namespace: ${ANSIBLE_NAMESPACE}
    spec:
      encryptedData:
        vault-password.txt: AgCdoLpyERUB3Cg+gVTXd7Y+o5absCA46NBmh8xyC//VgaDpTNmu4xzwHF7yG2vxFSPPsHk5dqnZTtricBPG+gNcODGm11pA5R6aU8sFRk0f4P0K9jq4y48DKTlLBezAKdfIGQ/vF5AnTs6phDnkt4iG1kCszlmmb9XWielOsotTTTx7dhXAqAz2n+NcUYfzAKeBc6TNna45ZF+VcY5qzVXzDbGsatKeUEn4DmwTP7ap5Kqeo89MyZw91UWBc6LRA1Bw3S1d5r1halMQzt85Is13DnOb7ZxHMDuuekX19lPOs/IuUcJ7dfWpLDaY84Tx59+GrnAfm+XQhScawSXzU6YCIBocZJgxxWR0iVUvzOVD2wDku2J9yRhLLvmTs1CMyY+mxVVbToP+ItPw1gLOhaHVLNF8oe//XmZ3kISq7lVcoOFQZd9eXlq1ZDiwaM+PSRW9XSUAU1dTRiIUNC9VY0+gIrb5UyWAzAUCNIpbJUj704CA0Otatl3sII2Qbvo10kir6H8eEjhRl/w2bO9MPL8sQxYVRbrUKqQFtOOv/a6DPNjQsAFWSbefJwqJQ3Tcv3dnoGnvX3O6i+VrrbX1Yy18ryqsaNhftTCnAPtUTonBEhuoqhhKy4hMviNrkxCwF9Ud606Sg6uFAljpVRFzOAEgPVmGicE4ieTpJFIl54oOyX7wurkn0652R5Z1Gl6pMU68Q+VTJsFn7oSnug==
      template:
        metadata:
          name: vault-password
          namespace: ${ANSIBLE_NAMESPACE}

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ansible
      namespace: ${ANSIBLE_NAMESPACE}
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
            - name: git-clone
              image: "docker.io/alpine/git:v2.47.1"
              args:
              - clone
              - https://github.com/too-common-name/openshift-ldap-playground.git 
              - /repo
              volumeMounts:
                - name: git-repo-volume
                  mountPath: /repo   
          containers:
            - name: ansible
              image: "docker.io/alpine/ansible:2.16.1"
              args:
              - "ansible-playbook"
              - "/repo/ansible-day2/populateldap.yaml"
              - "--vault-password-file"
              - "/vault/vault-password.txt"
              volumeMounts:
                - name: git-repo-volume
                  mountPath: /repo 
                - name: vault-password
                  mountPath: /vault  
          serviceAccountName: ansible
          volumes:
            - name: git-repo-volume
              emptyDir: {}  
            - name: vault-password
              secret:
                secretName: vault-password
