---
- name: Create LDAP tree structure
  hosts: localhost
  connection: local
  vars_files:
    - vault.yaml 
    - vars/ldap_info.yaml
  vars:
    - ansible_python_interpreter: /usr/local/bin/python
  tasks:
    - name: Ensure GCC and development tools are installed
      become: true
      package:
        name:
          - gcc
          - make
          - g++
          - "{{ python_dev_package }}"
          - "{{ openldap_dev_package }}"
        state: present
    - name: Ensure python-ldap
      pip:
        name:
          - python-ldap
          - passlib # crypt will be removed starting from 2.17
        state: present
    - name: LDAP node creation
      community.general.ldap_entry:
        dn: "{{ item.dn }}"
        objectClass: "{{ item.object_class }}"
        attributes: "{{ item.attributes }}"
        server_uri: "{{ ldap_server_uri }}"
        bind_dn: "{{ ldap_bind_dn }}"
        bind_pw: "{{ ldap_bind_pw }}"
      loop: "{{ ldap_tree }}"

  pre_tasks:
    - name: Set Python development package based on OS
      set_fact:
        python_dev_package: >-
          {% if ansible_facts.os_family == 'Alpine' %}
            python3-dev
          {% elif ansible_facts.os_family == 'Debian' %}
            python3-dev
          {% else %}
            python-devel
          {% endif %}
    
    - name: Set OpenLDAP development package based on OS
      set_fact:
        openldap_dev_package: >-
          {% if ansible_facts.os_family == 'Alpine' %}
            openldap-dev
          {% elif ansible_facts.os_family == 'Debian' %}
            libldap2-dev
          {% else %}
            openldap-devel
          {% endif %}