apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ldap-secret.yaml
  - oauth-cluster.yaml

patches:
  - target:
      kind: OAuth
      name: cluster
    path: cluster-patch.yaml
