apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgBMA2AqF/XdNYWvOPIcwJtKBkiCd7wvUHhs+W9PF8fQEWf0YBShlg+j3JOwJVnVUjcat3L+1z0MXACmvr3UV/AtYnCIdkvCYlzom22d4sQYZxgMwXNsbCuJBMy94UFz8vhDy/gfNHonbe7bV9z+3ENmyC8mJBUmoWReXC79ReFZwbbMfW6qIV1YAAihZVQG+wcpbj65hbYAC1CL6ET5TmMPu+BgxetaNpHuBAOmED6GafyuKAb/iRqmT7McqP3OCvLMbedpZhAIERD1kwLcQetCUZ2JbgzFqVUpaiM3UTTRLMazDvBITXHnoP5PIollTrNrTZffMuSgRb356TPWqKle2r4CYjxsbvsJx2UXea+76vyhgui+ES5DojKhwr86PKHl34tR/PHRX3o8OebsJQkPCWOXXb7S6r8ADjSgg0cJQSgCS5cIl00t6JlVjyXBC7p9u0XCyRiHQdNg5jJFG2k36walhCDeC/N7pcobCqKU11r7ajnTbES9lYlQMptz1SsUQiObtQ8DQELESZ/GVJHfh0JPWINls9UIaEDdjxMfCt+1/oVdDfCD6O5F3Az6Vx5PLolXgSa8pBiluxQSGwh0zteYjWif0lKo1TSgt1F0F1r1JhX73zuAWwSfOS8JRSy0oX7tdWcrX+qQ1XGecEcNCzGODPOZEIcHjtW/pm1P+CR3jknw4AVGomHjdZD78dfyew+fzUjMhfiZCg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ldap-secret
      namespace: openshift-config

