apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgCb+9K3YOMplqHTv4uA86SuvVA6ANaD+nwULcjwq0J6+JPPw2V9b/3dxfF9/0mm/tOhuDm9FN/EJ0DxhzQ0doOCbxpNg78/Rh9aesarj3NEeh93/ToTd7KqQXGsG5JbhecUOU62RRP4FW+v7ASr2UVb/umY7Xp1g0Gbg/swvUSgZWnWeYL9ZOXHr7pg4PhmnvPyAwOSeqizRP9ZQ7LZl+xlnWWrCWRMol/OLo/b816uXwP0sMuPtwaKyQ40SALBkltaiLxKyrNMllh/F4YE32L8VGaSor8+K8EyvfIqTVGMIPp7YJ8w4zwWsU636bptxfeotiHMQYhqr2VKoaZB7aNSzlA1ZnI4hSOwWFcYLqMfNrPEVfgrFxw4VkxKlrW2yFD7cfu3Ca70XyDZJTL0zCERavUHODd8dANmktN7d+VIzVopCOg95kWyLsBijxAYdR7vxt6hztaK+GQH2em5Ekg4B+lSbyRbPP1vWxSb2X8WONhkOQrtXaKBE+fqg+4RuVC5UaLmdQ44n2xeToBilv3Rl7oJ5g1Hs2144mIMIzGEb4LHF8kPDUtReVMitHN2mhiT3PlTJQ53SDsa0ce3mVzrXXT9gUzbM1F58t6/YSXfENewUMKEesSPv3ObYXymXUjy8GeAH5sREVUXX163GJnP6jEKD94UsOM/wPsq/EciWEvH+B/cW0G0zw2VFMPtuVV79K/w1t1a8n2Azg==
  template:
    metadata:
      name: ldap-secret
      namespace: openshift-config

