apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  creationTimestamp: "2024-08-19T05:54:56Z"
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: developer
      type: HTPasswd
  templates:
    login:
      name: login-template
  tokenConfig:
    accessTokenMaxAgeSeconds: 0
